# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_math_render_pb2 as service__math__render__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_math_render_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GRPCMathRenderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.meta_data_render = channel.unary_unary(
                '/mathrender.GRPCMathRender/meta_data_render',
                request_serializer=service__math__render__pb2.meta_data_render_request.SerializeToString,
                response_deserializer=service__math__render__pb2.meta_data_render_response.FromString,
                _registered_method=True)
        self.render_latex = channel.unary_unary(
                '/mathrender.GRPCMathRender/render_latex',
                request_serializer=service__math__render__pb2.render_latex_request.SerializeToString,
                response_deserializer=service__math__render__pb2.render_latex_response.FromString,
                _registered_method=True)


class GRPCMathRenderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def meta_data_render(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def render_latex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCMathRenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'meta_data_render': grpc.unary_unary_rpc_method_handler(
                    servicer.meta_data_render,
                    request_deserializer=service__math__render__pb2.meta_data_render_request.FromString,
                    response_serializer=service__math__render__pb2.meta_data_render_response.SerializeToString,
            ),
            'render_latex': grpc.unary_unary_rpc_method_handler(
                    servicer.render_latex,
                    request_deserializer=service__math__render__pb2.render_latex_request.FromString,
                    response_serializer=service__math__render__pb2.render_latex_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mathrender.GRPCMathRender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mathrender.GRPCMathRender', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GRPCMathRender(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def meta_data_render(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mathrender.GRPCMathRender/meta_data_render',
            service__math__render__pb2.meta_data_render_request.SerializeToString,
            service__math__render__pb2.meta_data_render_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def render_latex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mathrender.GRPCMathRender/render_latex',
            service__math__render__pb2.render_latex_request.SerializeToString,
            service__math__render__pb2.render_latex_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
