# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import gateway_pb2 as protos_dot_gateway__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExternalApiGatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register = channel.unary_unary(
                '/gateway.ExternalApiGateway/register',
                request_serializer=protos_dot_gateway__pb2.register_request.SerializeToString,
                response_deserializer=protos_dot_gateway__pb2.register_response.FromString,
                _registered_method=True)
        self.login = channel.unary_unary(
                '/gateway.ExternalApiGateway/login',
                request_serializer=protos_dot_gateway__pb2.login_request.SerializeToString,
                response_deserializer=protos_dot_gateway__pb2.login_response.FromString,
                _registered_method=True)
        self.is_admin = channel.unary_unary(
                '/gateway.ExternalApiGateway/is_admin',
                request_serializer=protos_dot_gateway__pb2.is_admin_request.SerializeToString,
                response_deserializer=protos_dot_gateway__pb2.is_admin_response.FromString,
                _registered_method=True)


class ExternalApiGatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_admin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExternalApiGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'register': grpc.unary_unary_rpc_method_handler(
                    servicer.register,
                    request_deserializer=protos_dot_gateway__pb2.register_request.FromString,
                    response_serializer=protos_dot_gateway__pb2.register_response.SerializeToString,
            ),
            'login': grpc.unary_unary_rpc_method_handler(
                    servicer.login,
                    request_deserializer=protos_dot_gateway__pb2.login_request.FromString,
                    response_serializer=protos_dot_gateway__pb2.login_response.SerializeToString,
            ),
            'is_admin': grpc.unary_unary_rpc_method_handler(
                    servicer.is_admin,
                    request_deserializer=protos_dot_gateway__pb2.is_admin_request.FromString,
                    response_serializer=protos_dot_gateway__pb2.is_admin_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gateway.ExternalApiGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gateway.ExternalApiGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExternalApiGateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.ExternalApiGateway/register',
            protos_dot_gateway__pb2.register_request.SerializeToString,
            protos_dot_gateway__pb2.register_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.ExternalApiGateway/login',
            protos_dot_gateway__pb2.login_request.SerializeToString,
            protos_dot_gateway__pb2.login_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def is_admin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.ExternalApiGateway/is_admin',
            protos_dot_gateway__pb2.is_admin_request.SerializeToString,
            protos_dot_gateway__pb2.is_admin_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
