# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/gateway.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'protos/gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/gateway.proto\x12\x07gateway\"R\n\x10register_request\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07surname\x18\x04 \x01(\t\"$\n\x11register_response\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"@\n\rlogin_request\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x03 \x01(\x03\"\x1f\n\x0elogin_response\x12\r\n\x05token\x18\x01 \x01(\t\"#\n\x10is_admin_request\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"%\n\x11is_admin_response\x12\x10\n\x08is_admin\x18\x01 \x01(\x08\x32\xd4\x01\n\x12\x45xternalApiGateway\x12\x41\n\x08register\x12\x19.gateway.register_request\x1a\x1a.gateway.register_response\x12\x38\n\x05login\x12\x16.gateway.login_request\x1a\x17.gateway.login_response\x12\x41\n\x08is_admin\x12\x19.gateway.is_admin_request\x1a\x1a.gateway.is_admin_responseB\x19Z\x17usov.gateway.v1;gatewayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027usov.gateway.v1;gateway'
  _globals['_REGISTER_REQUEST']._serialized_start=33
  _globals['_REGISTER_REQUEST']._serialized_end=115
  _globals['_REGISTER_RESPONSE']._serialized_start=117
  _globals['_REGISTER_RESPONSE']._serialized_end=153
  _globals['_LOGIN_REQUEST']._serialized_start=155
  _globals['_LOGIN_REQUEST']._serialized_end=219
  _globals['_LOGIN_RESPONSE']._serialized_start=221
  _globals['_LOGIN_RESPONSE']._serialized_end=252
  _globals['_IS_ADMIN_REQUEST']._serialized_start=254
  _globals['_IS_ADMIN_REQUEST']._serialized_end=289
  _globals['_IS_ADMIN_RESPONSE']._serialized_start=291
  _globals['_IS_ADMIN_RESPONSE']._serialized_end=328
  _globals['_EXTERNALAPIGATEWAY']._serialized_start=331
  _globals['_EXTERNALAPIGATEWAY']._serialized_end=543
# @@protoc_insertion_point(module_scope)
