# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/service_math_render.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'protos/service_math_render.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n protos/service_math_render.proto\x12\nmathrender\"\x1a\n\x18meta_data_render_request\":\n\x19meta_data_render_response\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"0\n\x14render_latex_request\x12\x18\n\x10latex_expression\x18\x01 \x01(\t\"-\n\x15render_latex_response\x12\x14\n\x0crender_image\x18\x01 \x01(\t2\xc6\x01\n\x0eGRPCMathRender\x12_\n\x10meta_data_render\x12$.mathrender.meta_data_render_request\x1a%.mathrender.meta_data_render_response\x12S\n\x0crender_latex\x12 .mathrender.render_latex_request\x1a!.mathrender.render_latex_responseB<Z:github.com/dagahan/EyeMath_protos/go/mathrender;mathrenderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.service_math_render_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/dagahan/EyeMath_protos/go/mathrender;mathrender'
  _globals['_META_DATA_RENDER_REQUEST']._serialized_start=48
  _globals['_META_DATA_RENDER_REQUEST']._serialized_end=74
  _globals['_META_DATA_RENDER_RESPONSE']._serialized_start=76
  _globals['_META_DATA_RENDER_RESPONSE']._serialized_end=134
  _globals['_RENDER_LATEX_REQUEST']._serialized_start=136
  _globals['_RENDER_LATEX_REQUEST']._serialized_end=184
  _globals['_RENDER_LATEX_RESPONSE']._serialized_start=186
  _globals['_RENDER_LATEX_RESPONSE']._serialized_end=231
  _globals['_GRPCMATHRENDER']._serialized_start=234
  _globals['_GRPCMATHRENDER']._serialized_end=432
# @@protoc_insertion_point(module_scope)
