# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/service_math_recognize.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'protos/service_math_recognize.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#protos/service_math_recognize.proto\x12\rmathrecognize\"\x1d\n\x1bmeta_data_recognize_request\"=\n\x1cmeta_data_recognize_response\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"?\n\x11recognize_request\x12\x1b\n\x13normalize_for_sympy\x18\x01 \x01(\x08\x12\r\n\x05image\x18\x02 \x01(\t\"$\n\x12recognize_response\x12\x0e\n\x06result\x18\x01 \x01(\t\"7\n\x1bnormalize_for_sympy_request\x12\x18\n\x10latex_expression\x18\x01 \x01(\t\".\n\x1cnormalize_for_sympy_response\x12\x0e\n\x06result\x18\x01 \x01(\t2\xc5\x02\n\x11GRPCMathRecognize\x12n\n\x13meta_data_recognize\x12*.mathrecognize.meta_data_recognize_request\x1a+.mathrecognize.meta_data_recognize_response\x12P\n\trecognize\x12 .mathrecognize.recognize_request\x1a!.mathrecognize.recognize_response\x12n\n\x13normalize_for_sympy\x12*.mathrecognize.normalize_for_sympy_request\x1a+.mathrecognize.normalize_for_sympy_responseBBZ@github.com/dagahan/EyeMath_protos/go/mathrecognize;mathrecognizeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.service_math_recognize_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z@github.com/dagahan/EyeMath_protos/go/mathrecognize;mathrecognize'
  _globals['_META_DATA_RECOGNIZE_REQUEST']._serialized_start=54
  _globals['_META_DATA_RECOGNIZE_REQUEST']._serialized_end=83
  _globals['_META_DATA_RECOGNIZE_RESPONSE']._serialized_start=85
  _globals['_META_DATA_RECOGNIZE_RESPONSE']._serialized_end=146
  _globals['_RECOGNIZE_REQUEST']._serialized_start=148
  _globals['_RECOGNIZE_REQUEST']._serialized_end=211
  _globals['_RECOGNIZE_RESPONSE']._serialized_start=213
  _globals['_RECOGNIZE_RESPONSE']._serialized_end=249
  _globals['_NORMALIZE_FOR_SYMPY_REQUEST']._serialized_start=251
  _globals['_NORMALIZE_FOR_SYMPY_REQUEST']._serialized_end=306
  _globals['_NORMALIZE_FOR_SYMPY_RESPONSE']._serialized_start=308
  _globals['_NORMALIZE_FOR_SYMPY_RESPONSE']._serialized_end=354
  _globals['_GRPCMATHRECOGNIZE']._serialized_start=357
  _globals['_GRPCMATHRECOGNIZE']._serialized_end=682
# @@protoc_insertion_point(module_scope)
