// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: service_math_recognize.proto

package mathrecognize

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetaDataRecognizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaDataRecognizeRequest) Reset() {
	*x = MetaDataRecognizeRequest{}
	mi := &file_service_math_recognize_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaDataRecognizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaDataRecognizeRequest) ProtoMessage() {}

func (x *MetaDataRecognizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_math_recognize_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaDataRecognizeRequest.ProtoReflect.Descriptor instead.
func (*MetaDataRecognizeRequest) Descriptor() ([]byte, []int) {
	return file_service_math_recognize_proto_rawDescGZIP(), []int{0}
}

type MetaDataRecognizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaDataRecognizeResponse) Reset() {
	*x = MetaDataRecognizeResponse{}
	mi := &file_service_math_recognize_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaDataRecognizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaDataRecognizeResponse) ProtoMessage() {}

func (x *MetaDataRecognizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_math_recognize_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaDataRecognizeResponse.ProtoReflect.Descriptor instead.
func (*MetaDataRecognizeResponse) Descriptor() ([]byte, []int) {
	return file_service_math_recognize_proto_rawDescGZIP(), []int{1}
}

func (x *MetaDataRecognizeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetaDataRecognizeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RecognizeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NormalizeForSympy bool                   `protobuf:"varint,1,opt,name=normalize_for_sympy,json=normalizeForSympy,proto3" json:"normalize_for_sympy,omitempty"`
	ImageInBytes      []byte                 `protobuf:"bytes,2,opt,name=image_in_bytes,json=imageInBytes,proto3" json:"image_in_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecognizeRequest) Reset() {
	*x = RecognizeRequest{}
	mi := &file_service_math_recognize_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeRequest) ProtoMessage() {}

func (x *RecognizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_math_recognize_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeRequest.ProtoReflect.Descriptor instead.
func (*RecognizeRequest) Descriptor() ([]byte, []int) {
	return file_service_math_recognize_proto_rawDescGZIP(), []int{2}
}

func (x *RecognizeRequest) GetNormalizeForSympy() bool {
	if x != nil {
		return x.NormalizeForSympy
	}
	return false
}

func (x *RecognizeRequest) GetImageInBytes() []byte {
	if x != nil {
		return x.ImageInBytes
	}
	return nil
}

type RecognizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeResponse) Reset() {
	*x = RecognizeResponse{}
	mi := &file_service_math_recognize_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeResponse) ProtoMessage() {}

func (x *RecognizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_math_recognize_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeResponse.ProtoReflect.Descriptor instead.
func (*RecognizeResponse) Descriptor() ([]byte, []int) {
	return file_service_math_recognize_proto_rawDescGZIP(), []int{3}
}

func (x *RecognizeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type NormalizeForSympyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LatexExpression string                 `protobuf:"bytes,1,opt,name=latex_expression,json=latexExpression,proto3" json:"latex_expression,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NormalizeForSympyRequest) Reset() {
	*x = NormalizeForSympyRequest{}
	mi := &file_service_math_recognize_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizeForSympyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizeForSympyRequest) ProtoMessage() {}

func (x *NormalizeForSympyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_math_recognize_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizeForSympyRequest.ProtoReflect.Descriptor instead.
func (*NormalizeForSympyRequest) Descriptor() ([]byte, []int) {
	return file_service_math_recognize_proto_rawDescGZIP(), []int{4}
}

func (x *NormalizeForSympyRequest) GetLatexExpression() string {
	if x != nil {
		return x.LatexExpression
	}
	return ""
}

type NormalizeForSympyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizeForSympyResponse) Reset() {
	*x = NormalizeForSympyResponse{}
	mi := &file_service_math_recognize_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizeForSympyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizeForSympyResponse) ProtoMessage() {}

func (x *NormalizeForSympyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_math_recognize_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizeForSympyResponse.ProtoReflect.Descriptor instead.
func (*NormalizeForSympyResponse) Descriptor() ([]byte, []int) {
	return file_service_math_recognize_proto_rawDescGZIP(), []int{5}
}

func (x *NormalizeForSympyResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type RenderLatexRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LatexExpression string                 `protobuf:"bytes,1,opt,name=latex_expression,json=latexExpression,proto3" json:"latex_expression,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RenderLatexRequest) Reset() {
	*x = RenderLatexRequest{}
	mi := &file_service_math_recognize_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderLatexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderLatexRequest) ProtoMessage() {}

func (x *RenderLatexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_math_recognize_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderLatexRequest.ProtoReflect.Descriptor instead.
func (*RenderLatexRequest) Descriptor() ([]byte, []int) {
	return file_service_math_recognize_proto_rawDescGZIP(), []int{6}
}

func (x *RenderLatexRequest) GetLatexExpression() string {
	if x != nil {
		return x.LatexExpression
	}
	return ""
}

type RenderLatexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RenderImage   string                 `protobuf:"bytes,1,opt,name=render_image,json=renderImage,proto3" json:"render_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderLatexResponse) Reset() {
	*x = RenderLatexResponse{}
	mi := &file_service_math_recognize_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderLatexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderLatexResponse) ProtoMessage() {}

func (x *RenderLatexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_math_recognize_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderLatexResponse.ProtoReflect.Descriptor instead.
func (*RenderLatexResponse) Descriptor() ([]byte, []int) {
	return file_service_math_recognize_proto_rawDescGZIP(), []int{7}
}

func (x *RenderLatexResponse) GetRenderImage() string {
	if x != nil {
		return x.RenderImage
	}
	return ""
}

var File_service_math_recognize_proto protoreflect.FileDescriptor

const file_service_math_recognize_proto_rawDesc = "" +
	"\n" +
	"\x1cservice_math_recognize.proto\x12\rmathrecognize\"\x1d\n" +
	"\x1bmeta_data_recognize_request\"L\n" +
	"\x1cmeta_data_recognize_response\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"i\n" +
	"\x11recognize_request\x12.\n" +
	"\x13normalize_for_sympy\x18\x01 \x01(\bR\x11normalizeForSympy\x12$\n" +
	"\x0eimage_in_bytes\x18\x02 \x01(\fR\fimageInBytes\",\n" +
	"\x12recognize_response\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"H\n" +
	"\x1bnormalize_for_sympy_request\x12)\n" +
	"\x10latex_expression\x18\x01 \x01(\tR\x0flatexExpression\"6\n" +
	"\x1cnormalize_for_sympy_response\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"A\n" +
	"\x14render_latex_request\x12)\n" +
	"\x10latex_expression\x18\x01 \x01(\tR\x0flatexExpression\":\n" +
	"\x15render_latex_response\x12!\n" +
	"\frender_image\x18\x01 \x01(\tR\vrenderImage2\xa0\x03\n" +
	"\x11GRPCMathRecognize\x12n\n" +
	"\x13meta_data_recognize\x12*.mathrecognize.meta_data_recognize_request\x1a+.mathrecognize.meta_data_recognize_response\x12P\n" +
	"\trecognize\x12 .mathrecognize.recognize_request\x1a!.mathrecognize.recognize_response\x12n\n" +
	"\x13normalize_for_sympy\x12*.mathrecognize.normalize_for_sympy_request\x1a+.mathrecognize.normalize_for_sympy_response\x12Y\n" +
	"\frender_latex\x12#.mathrecognize.render_latex_request\x1a$.mathrecognize.render_latex_responseBBZ@github.com/dagahan/EyeMath_protos/go/mathrecognize;mathrecognizeb\x06proto3"

var (
	file_service_math_recognize_proto_rawDescOnce sync.Once
	file_service_math_recognize_proto_rawDescData []byte
)

func file_service_math_recognize_proto_rawDescGZIP() []byte {
	file_service_math_recognize_proto_rawDescOnce.Do(func() {
		file_service_math_recognize_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_math_recognize_proto_rawDesc), len(file_service_math_recognize_proto_rawDesc)))
	})
	return file_service_math_recognize_proto_rawDescData
}

var file_service_math_recognize_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_service_math_recognize_proto_goTypes = []any{
	(*MetaDataRecognizeRequest)(nil),  // 0: mathrecognize.meta_data_recognize_request
	(*MetaDataRecognizeResponse)(nil), // 1: mathrecognize.meta_data_recognize_response
	(*RecognizeRequest)(nil),          // 2: mathrecognize.recognize_request
	(*RecognizeResponse)(nil),         // 3: mathrecognize.recognize_response
	(*NormalizeForSympyRequest)(nil),  // 4: mathrecognize.normalize_for_sympy_request
	(*NormalizeForSympyResponse)(nil), // 5: mathrecognize.normalize_for_sympy_response
	(*RenderLatexRequest)(nil),        // 6: mathrecognize.render_latex_request
	(*RenderLatexResponse)(nil),       // 7: mathrecognize.render_latex_response
}
var file_service_math_recognize_proto_depIdxs = []int32{
	0, // 0: mathrecognize.GRPCMathRecognize.meta_data_recognize:input_type -> mathrecognize.meta_data_recognize_request
	2, // 1: mathrecognize.GRPCMathRecognize.recognize:input_type -> mathrecognize.recognize_request
	4, // 2: mathrecognize.GRPCMathRecognize.normalize_for_sympy:input_type -> mathrecognize.normalize_for_sympy_request
	6, // 3: mathrecognize.GRPCMathRecognize.render_latex:input_type -> mathrecognize.render_latex_request
	1, // 4: mathrecognize.GRPCMathRecognize.meta_data_recognize:output_type -> mathrecognize.meta_data_recognize_response
	3, // 5: mathrecognize.GRPCMathRecognize.recognize:output_type -> mathrecognize.recognize_response
	5, // 6: mathrecognize.GRPCMathRecognize.normalize_for_sympy:output_type -> mathrecognize.normalize_for_sympy_response
	7, // 7: mathrecognize.GRPCMathRecognize.render_latex:output_type -> mathrecognize.render_latex_response
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_math_recognize_proto_init() }
func file_service_math_recognize_proto_init() {
	if File_service_math_recognize_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_math_recognize_proto_rawDesc), len(file_service_math_recognize_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_math_recognize_proto_goTypes,
		DependencyIndexes: file_service_math_recognize_proto_depIdxs,
		MessageInfos:      file_service_math_recognize_proto_msgTypes,
	}.Build()
	File_service_math_recognize_proto = out.File
	file_service_math_recognize_proto_goTypes = nil
	file_service_math_recognize_proto_depIdxs = nil
}
