# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import service_math_solve_pb2 as service__math__solve__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_math_solve_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GRPCMathSolveStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.meta_data_solve = channel.unary_unary(
                '/mathsolve.GRPCMathSolve/meta_data_solve',
                request_serializer=service__math__solve__pb2.meta_data_solve_request.SerializeToString,
                response_deserializer=service__math__solve__pb2.meta_data_solve_response.FromString,
                _registered_method=True)
        self.solve = channel.unary_unary(
                '/mathsolve.GRPCMathSolve/solve',
                request_serializer=service__math__solve__pb2.solve_request.SerializeToString,
                response_deserializer=service__math__solve__pb2.solve_response.FromString,
                _registered_method=True)


class GRPCMathSolveServicer(object):
    """Missing associated documentation comment in .proto file."""

    def meta_data_solve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def solve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCMathSolveServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'meta_data_solve': grpc.unary_unary_rpc_method_handler(
                    servicer.meta_data_solve,
                    request_deserializer=service__math__solve__pb2.meta_data_solve_request.FromString,
                    response_serializer=service__math__solve__pb2.meta_data_solve_response.SerializeToString,
            ),
            'solve': grpc.unary_unary_rpc_method_handler(
                    servicer.solve,
                    request_deserializer=service__math__solve__pb2.solve_request.FromString,
                    response_serializer=service__math__solve__pb2.solve_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mathsolve.GRPCMathSolve', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mathsolve.GRPCMathSolve', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GRPCMathSolve(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def meta_data_solve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mathsolve.GRPCMathSolve/meta_data_solve',
            service__math__solve__pb2.meta_data_solve_request.SerializeToString,
            service__math__solve__pb2.meta_data_solve_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def solve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mathsolve.GRPCMathSolve/solve',
            service__math__solve__pb2.solve_request.SerializeToString,
            service__math__solve__pb2.solve_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
