# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service_math_solve.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'service_math_solve.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18service_math_solve.proto\x12\tmathsolve\"\x19\n\x17meta_data_solve_request\"9\n\x18meta_data_solve_response\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"g\n\rsolve_request\x12\x18\n\x10latex_expression\x18\x01 \x01(\t\x12\x1a\n\x12show_solving_steps\x18\x02 \x01(\x08\x12 \n\x18render_latex_expressions\x18\x03 \x01(\x08\"I\n\x0esolve_response\x12\x0f\n\x07results\x18\x01 \x03(\t\x12\x0f\n\x07renders\x18\x02 \x03(\t\x12\x15\n\rsolving_steps\x18\x03 \x03(\t2\xa9\x01\n\rGRPCMathSolve\x12Z\n\x0fmeta_data_solve\x12\".mathsolve.meta_data_solve_request\x1a#.mathsolve.meta_data_solve_response\x12<\n\x05solve\x12\x18.mathsolve.solve_request\x1a\x19.mathsolve.solve_responseB:Z8github.com/dagahan/EyeMath_protos/go/mathsolve;mathsolveb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_math_solve_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/dagahan/EyeMath_protos/go/mathsolve;mathsolve'
  _globals['_META_DATA_SOLVE_REQUEST']._serialized_start=39
  _globals['_META_DATA_SOLVE_REQUEST']._serialized_end=64
  _globals['_META_DATA_SOLVE_RESPONSE']._serialized_start=66
  _globals['_META_DATA_SOLVE_RESPONSE']._serialized_end=123
  _globals['_SOLVE_REQUEST']._serialized_start=125
  _globals['_SOLVE_REQUEST']._serialized_end=228
  _globals['_SOLVE_RESPONSE']._serialized_start=230
  _globals['_SOLVE_RESPONSE']._serialized_end=303
  _globals['_GRPCMATHSOLVE']._serialized_start=306
  _globals['_GRPCMATHSOLVE']._serialized_end=475
# @@protoc_insertion_point(module_scope)
