# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_math_recognize_pb2 as service__math__recognize__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_math_recognize_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GRPCMathRecognizeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.meta_data_recognize = channel.unary_unary(
                '/mathrecognize.GRPCMathRecognize/meta_data_recognize',
                request_serializer=service__math__recognize__pb2.meta_data_recognize_request.SerializeToString,
                response_deserializer=service__math__recognize__pb2.meta_data_recognize_response.FromString,
                _registered_method=True)
        self.recognize = channel.unary_unary(
                '/mathrecognize.GRPCMathRecognize/recognize',
                request_serializer=service__math__recognize__pb2.recognize_request.SerializeToString,
                response_deserializer=service__math__recognize__pb2.recognize_response.FromString,
                _registered_method=True)
        self.normalize_for_sympy = channel.unary_unary(
                '/mathrecognize.GRPCMathRecognize/normalize_for_sympy',
                request_serializer=service__math__recognize__pb2.normalize_for_sympy_request.SerializeToString,
                response_deserializer=service__math__recognize__pb2.normalize_for_sympy_response.FromString,
                _registered_method=True)


class GRPCMathRecognizeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def meta_data_recognize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def recognize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def normalize_for_sympy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCMathRecognizeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'meta_data_recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.meta_data_recognize,
                    request_deserializer=service__math__recognize__pb2.meta_data_recognize_request.FromString,
                    response_serializer=service__math__recognize__pb2.meta_data_recognize_response.SerializeToString,
            ),
            'recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.recognize,
                    request_deserializer=service__math__recognize__pb2.recognize_request.FromString,
                    response_serializer=service__math__recognize__pb2.recognize_response.SerializeToString,
            ),
            'normalize_for_sympy': grpc.unary_unary_rpc_method_handler(
                    servicer.normalize_for_sympy,
                    request_deserializer=service__math__recognize__pb2.normalize_for_sympy_request.FromString,
                    response_serializer=service__math__recognize__pb2.normalize_for_sympy_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mathrecognize.GRPCMathRecognize', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mathrecognize.GRPCMathRecognize', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GRPCMathRecognize(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def meta_data_recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mathrecognize.GRPCMathRecognize/meta_data_recognize',
            service__math__recognize__pb2.meta_data_recognize_request.SerializeToString,
            service__math__recognize__pb2.meta_data_recognize_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mathrecognize.GRPCMathRecognize/recognize',
            service__math__recognize__pb2.recognize_request.SerializeToString,
            service__math__recognize__pb2.recognize_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def normalize_for_sympy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mathrecognize.GRPCMathRecognize/normalize_for_sympy',
            service__math__recognize__pb2.normalize_for_sympy_request.SerializeToString,
            service__math__recognize__pb2.normalize_for_sympy_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
