# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: external_api_gateway.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'external_api_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x65xternal_api_gateway.proto\x12\x12\x45xternalApiGateway\"R\n\x10register_request\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07surname\x18\x04 \x01(\t\"$\n\x11register_response\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"@\n\rlogin_request\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x03 \x01(\x03\"\x1f\n\x0elogin_response\x12\r\n\x05token\x18\x01 \x01(\t\"#\n\x10is_admin_request\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"%\n\x11is_admin_response\x12\x10\n\x08is_admin\x18\x01 \x01(\x08\")\n\x13math_solver_request\x12\x12\n\nexpression\x18\x01 \x01(\t\"&\n\x14math_solver_response\x12\x0e\n\x06result\x18\x01 \x01(\t\"(\n\x17math_recognizer_request\x12\r\n\x05image\x18\x01 \x01(\x0c\"*\n\x18math_recognizer_response\x12\x0e\n\x06result\x18\x01 \x01(\t2\xe6\x03\n\x12\x45xternalApiGateway\x12W\n\x08register\x12$.ExternalApiGateway.register_request\x1a%.ExternalApiGateway.register_response\x12N\n\x05login\x12!.ExternalApiGateway.login_request\x1a\".ExternalApiGateway.login_response\x12W\n\x08is_admin\x12$.ExternalApiGateway.is_admin_request\x1a%.ExternalApiGateway.is_admin_response\x12`\n\x0bmath_solver\x12\'.ExternalApiGateway.math_solver_request\x1a(.ExternalApiGateway.math_solver_response\x12l\n\x0fmath_recognizer\x12+.ExternalApiGateway.math_recognizer_request\x1a,.ExternalApiGateway.math_recognizer_responseB(Z&usov.external_api_gateway.v1;exapigateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'external_api_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&usov.external_api_gateway.v1;exapigate'
  _globals['_REGISTER_REQUEST']._serialized_start=50
  _globals['_REGISTER_REQUEST']._serialized_end=132
  _globals['_REGISTER_RESPONSE']._serialized_start=134
  _globals['_REGISTER_RESPONSE']._serialized_end=170
  _globals['_LOGIN_REQUEST']._serialized_start=172
  _globals['_LOGIN_REQUEST']._serialized_end=236
  _globals['_LOGIN_RESPONSE']._serialized_start=238
  _globals['_LOGIN_RESPONSE']._serialized_end=269
  _globals['_IS_ADMIN_REQUEST']._serialized_start=271
  _globals['_IS_ADMIN_REQUEST']._serialized_end=306
  _globals['_IS_ADMIN_RESPONSE']._serialized_start=308
  _globals['_IS_ADMIN_RESPONSE']._serialized_end=345
  _globals['_MATH_SOLVER_REQUEST']._serialized_start=347
  _globals['_MATH_SOLVER_REQUEST']._serialized_end=388
  _globals['_MATH_SOLVER_RESPONSE']._serialized_start=390
  _globals['_MATH_SOLVER_RESPONSE']._serialized_end=428
  _globals['_MATH_RECOGNIZER_REQUEST']._serialized_start=430
  _globals['_MATH_RECOGNIZER_REQUEST']._serialized_end=470
  _globals['_MATH_RECOGNIZER_RESPONSE']._serialized_start=472
  _globals['_MATH_RECOGNIZER_RESPONSE']._serialized_end=514
  _globals['_EXTERNALAPIGATEWAY']._serialized_start=517
  _globals['_EXTERNALAPIGATEWAY']._serialized_end=1003
# @@protoc_insertion_point(module_scope)
