// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: external_api_gateway.proto

package exapigate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,4,opt,name=surname,proto3" json:"surname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_external_api_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_api_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_external_api_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_external_api_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_api_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_external_api_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	AppId         int64                  `protobuf:"varint,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_external_api_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_api_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_external_api_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_external_api_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_api_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_external_api_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type IsAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAdminRequest) Reset() {
	*x = IsAdminRequest{}
	mi := &file_external_api_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAdminRequest) ProtoMessage() {}

func (x *IsAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_api_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAdminRequest.ProtoReflect.Descriptor instead.
func (*IsAdminRequest) Descriptor() ([]byte, []int) {
	return file_external_api_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *IsAdminRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type IsAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAdmin       bool                   `protobuf:"varint,1,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAdminResponse) Reset() {
	*x = IsAdminResponse{}
	mi := &file_external_api_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAdminResponse) ProtoMessage() {}

func (x *IsAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_api_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAdminResponse.ProtoReflect.Descriptor instead.
func (*IsAdminResponse) Descriptor() ([]byte, []int) {
	return file_external_api_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *IsAdminResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type MathSolverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expression    string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MathSolverRequest) Reset() {
	*x = MathSolverRequest{}
	mi := &file_external_api_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MathSolverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MathSolverRequest) ProtoMessage() {}

func (x *MathSolverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_api_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MathSolverRequest.ProtoReflect.Descriptor instead.
func (*MathSolverRequest) Descriptor() ([]byte, []int) {
	return file_external_api_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *MathSolverRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

type MathSolverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MathSolverResponse) Reset() {
	*x = MathSolverResponse{}
	mi := &file_external_api_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MathSolverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MathSolverResponse) ProtoMessage() {}

func (x *MathSolverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_api_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MathSolverResponse.ProtoReflect.Descriptor instead.
func (*MathSolverResponse) Descriptor() ([]byte, []int) {
	return file_external_api_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *MathSolverResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type MathRecognizerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MathRecognizerRequest) Reset() {
	*x = MathRecognizerRequest{}
	mi := &file_external_api_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MathRecognizerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MathRecognizerRequest) ProtoMessage() {}

func (x *MathRecognizerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_api_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MathRecognizerRequest.ProtoReflect.Descriptor instead.
func (*MathRecognizerRequest) Descriptor() ([]byte, []int) {
	return file_external_api_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *MathRecognizerRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type MathRecognizerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MathRecognizerResponse) Reset() {
	*x = MathRecognizerResponse{}
	mi := &file_external_api_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MathRecognizerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MathRecognizerResponse) ProtoMessage() {}

func (x *MathRecognizerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_api_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MathRecognizerResponse.ProtoReflect.Descriptor instead.
func (*MathRecognizerResponse) Descriptor() ([]byte, []int) {
	return file_external_api_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *MathRecognizerResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_external_api_gateway_proto protoreflect.FileDescriptor

const file_external_api_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1aexternal_api_gateway.proto\x12\x12ExternalApiGateway\"r\n" +
	"\x10register_request\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x04 \x01(\tR\asurname\",\n" +
	"\x11register_response\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"X\n" +
	"\rlogin_request\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\x03R\x05appId\"&\n" +
	"\x0elogin_response\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"+\n" +
	"\x10is_admin_request\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\".\n" +
	"\x11is_admin_response\x12\x19\n" +
	"\bis_admin\x18\x01 \x01(\bR\aisAdmin\"5\n" +
	"\x13math_solver_request\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\".\n" +
	"\x14math_solver_response\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"/\n" +
	"\x17math_recognizer_request\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\"2\n" +
	"\x18math_recognizer_response\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\xe6\x03\n" +
	"\x12ExternalApiGateway\x12W\n" +
	"\bregister\x12$.ExternalApiGateway.register_request\x1a%.ExternalApiGateway.register_response\x12N\n" +
	"\x05login\x12!.ExternalApiGateway.login_request\x1a\".ExternalApiGateway.login_response\x12W\n" +
	"\bis_admin\x12$.ExternalApiGateway.is_admin_request\x1a%.ExternalApiGateway.is_admin_response\x12`\n" +
	"\vmath_solver\x12'.ExternalApiGateway.math_solver_request\x1a(.ExternalApiGateway.math_solver_response\x12l\n" +
	"\x0fmath_recognizer\x12+.ExternalApiGateway.math_recognizer_request\x1a,.ExternalApiGateway.math_recognizer_responseB(Z&usov.external_api_gateway.v1;exapigateb\x06proto3"

var (
	file_external_api_gateway_proto_rawDescOnce sync.Once
	file_external_api_gateway_proto_rawDescData []byte
)

func file_external_api_gateway_proto_rawDescGZIP() []byte {
	file_external_api_gateway_proto_rawDescOnce.Do(func() {
		file_external_api_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_external_api_gateway_proto_rawDesc), len(file_external_api_gateway_proto_rawDesc)))
	})
	return file_external_api_gateway_proto_rawDescData
}

var file_external_api_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_external_api_gateway_proto_goTypes = []any{
	(*RegisterRequest)(nil),        // 0: ExternalApiGateway.register_request
	(*RegisterResponse)(nil),       // 1: ExternalApiGateway.register_response
	(*LoginRequest)(nil),           // 2: ExternalApiGateway.login_request
	(*LoginResponse)(nil),          // 3: ExternalApiGateway.login_response
	(*IsAdminRequest)(nil),         // 4: ExternalApiGateway.is_admin_request
	(*IsAdminResponse)(nil),        // 5: ExternalApiGateway.is_admin_response
	(*MathSolverRequest)(nil),      // 6: ExternalApiGateway.math_solver_request
	(*MathSolverResponse)(nil),     // 7: ExternalApiGateway.math_solver_response
	(*MathRecognizerRequest)(nil),  // 8: ExternalApiGateway.math_recognizer_request
	(*MathRecognizerResponse)(nil), // 9: ExternalApiGateway.math_recognizer_response
}
var file_external_api_gateway_proto_depIdxs = []int32{
	0, // 0: ExternalApiGateway.ExternalApiGateway.register:input_type -> ExternalApiGateway.register_request
	2, // 1: ExternalApiGateway.ExternalApiGateway.login:input_type -> ExternalApiGateway.login_request
	4, // 2: ExternalApiGateway.ExternalApiGateway.is_admin:input_type -> ExternalApiGateway.is_admin_request
	6, // 3: ExternalApiGateway.ExternalApiGateway.math_solver:input_type -> ExternalApiGateway.math_solver_request
	8, // 4: ExternalApiGateway.ExternalApiGateway.math_recognizer:input_type -> ExternalApiGateway.math_recognizer_request
	1, // 5: ExternalApiGateway.ExternalApiGateway.register:output_type -> ExternalApiGateway.register_response
	3, // 6: ExternalApiGateway.ExternalApiGateway.login:output_type -> ExternalApiGateway.login_response
	5, // 7: ExternalApiGateway.ExternalApiGateway.is_admin:output_type -> ExternalApiGateway.is_admin_response
	7, // 8: ExternalApiGateway.ExternalApiGateway.math_solver:output_type -> ExternalApiGateway.math_solver_response
	9, // 9: ExternalApiGateway.ExternalApiGateway.math_recognizer:output_type -> ExternalApiGateway.math_recognizer_response
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_external_api_gateway_proto_init() }
func file_external_api_gateway_proto_init() {
	if File_external_api_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_external_api_gateway_proto_rawDesc), len(file_external_api_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_external_api_gateway_proto_goTypes,
		DependencyIndexes: file_external_api_gateway_proto_depIdxs,
		MessageInfos:      file_external_api_gateway_proto_msgTypes,
	}.Build()
	File_external_api_gateway_proto = out.File
	file_external_api_gateway_proto_goTypes = nil
	file_external_api_gateway_proto_depIdxs = nil
}
